name: Announce App
description: Announces which app is being built

inputs:
  app-name:
    description: Name of the app
    required: true

runs:
  using: composite
  steps:
    - name: Announce app
      shell: bash
      run: echo "Building ${{ inputs.app-name }}"
