name: Announce

on: push

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Announce app
        uses: ./.github/actions/announce
        with:
          app-name: pixelpost
