name: pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.make-label.outputs.version }}
    steps:
      - name: hello
        id: make-label
        run: echo "version=1.4.2" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: runtest
        run: echo "hello"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: hi
        run: echo "${{ needs.build.outputs.version }}"
